import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import localFont from 'next/font/local'

const consolas = localFont({
  src: [
    { path: '../../public/fonts/consolas-regular.ttf', weight: '400', style: 'normal' },
    { path: '../../public/fonts/consolas-bold.ttf', weight: '700', style: 'normal' },
    { path: '../../public/fonts/consolas-italic.ttf', weight: '400', style: 'italic' },
    { path: '../../public/fonts/consolas-bold-italic.ttf', weight: '700', style: 'italic' },
  ],
  variable: '--font-consolas',
  display: 'swap',
})

const haettenschweiler = localFont({
  src: '../../public/fonts/haettenschweiler.ttf',
  variable: '--font-haettenschweiler',
  display: 'swap',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${haettenschweiler.variable} ${consolas.variable} h-full antialiased`} suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
